{{- if .Values.secret.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "telebot.fullname" .) }}
  labels:
    {{- include "telebot.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.secret.token | quote }}
{{- end }}
